export const faqs = [
  {
    question: "WHAT IS THE TOTAL SUPPLY OF SHARKS?",
    answer: "THERE ARE A TOTAL OF 10,000 NFTS AVAILABLE TO MINT.",
  },
  {
    question: "WHAT IS THE PRICE FOR ONE WICKED SHARK NFT?",
    answer: "WHITELIST 0.1 ETH (+Gas fee) | PUBLIC SALES 0.2 ETH (+Gas fee).",
  },
  {
    question: "WHAT DAY DOES WICKED SHARK CLUB LAUNCH?",
    answer: "WILL BE DETERMINED SOON ..",
  },
  {
    question: "HOW MANY PEOPLE WILL BE ALLOWED IN THE WHITELIST SALE?",
    answer:
      "THERE WILL ONLY BE 2500 PEOPLE ALLOWED/ELIGIBLE TO BE IN OUR WHITELIST SALE",
  },
  {
    question: "HOW MANY SHARKS NFTS CAN I MINT IN THE WHITELIST SALE?",
    answer: "YOU MAY MINT 1 NFT PER WALLET IF YOU ARE IN THE WHITELIST SALE.",
  },
  {
    question: "HOW MANY SHARKS NFTS CAN I MINT IN THE PUBLIC SALE?",
    answer:
      "YOU MAY MINT UP-TO 2 SHARKS NFTS PER WALLET IF YOU ARE IN THE PUBLIC SALE.",
  },
];
